version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "76:f3:aa:52:65:1f:70:08:51:fd:d6:e0:7c:8a:33:fb"

      - restore_cache: &restore_cache
          keys:
            - v1-{{ .Branch }}-

      - run:
          name: "Install requirements.txt"
          command: |
            python3.7 -m venv .venv;
            . .venv/bin/activate
            pip install -U pip
            pip install -e .[tests]

      - save_cache: &save_cache
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/project/.venv
            - ~/.cache/pip

      - run:
          name: "Check Linting"
          command: |
            . .venv/bin/activate
            mypy docs/examples

      - run:
          name: "Run tests against mock API"
          command: |
            . .venv/bin/activate
            export SKIP_TAGS=real; pytest -v

      - run:
          name: "Run all tests, including live API"
          command: |
            . .venv/bin/activate
            pytest -v --doctest-modules

      - run:
          name: "Run all examples"
          command: |
            set -xe
            . .venv/bin/activate
            for f in docs/examples/*.py; do cp -v -- "$f" "$f-example.py"; done
            cp docs/examples/*-example.py .
            for f in *-example.py; do python "$f"; done
            rm docs/examples/*-example.py
            rm *-example.py

      - run:
          name: "Confirm that the check_setup script works"
          command: |
            . .venv/bin/activate
            python -m vortexasdk.check_setup

      - run:
          name: "Build docs"
          command: |
            . .venv/bin/activate
            ./docs/scripts/build_docs.sh
